version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@chakra-ui/icons"
    versions:
    - 1.0.10
    - 1.0.11
    - 1.0.7
    - 1.0.8
    - 1.0.9
  - dependency-name: "@chakra-ui/react"
    versions:
    - 1.4.1
    - 1.4.2
    - 1.5.0
    - 1.5.1
    - 1.5.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: next-mdx-remote
    versions:
    - 2.1.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
    - 7.23.2
  - dependency-name: "@emotion/styled"
    versions:
    - 11.1.5
    - 11.3.0
  - dependency-name: framer-motion
    versions:
    - 4.0.3
    - 4.1.2
    - 4.1.3
  - dependency-name: apollo-server-micro
    versions:
    - 2.22.1
    - 2.22.2
  - dependency-name: "@emotion/react"
    versions:
    - 11.1.5
  - dependency-name: eslint
    versions:
    - 7.23.0
  - dependency-name: "@mdx-js/loader"
    versions:
    - 1.6.22
